kind: pipeline
name: default

steps:
    - name: ping
      image: mongo:4.4
      commands:
          - sleep 5
          - mongo --host mongo --eval "db.version()"

    - name: test
      image: python:3.7-buster
      commands:
          - pip install -qr requirements.txt
          - pytest -x --db-connection-string mongodb://mongo:27017 --redis-connection-string redis://redis:6379 --cov --cov-report xml

services:
  - name: mongo
    image: mongo:4.4
    command: [--nojournal]
    ports:
      - 27017